using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UPath.Api.Models;

[Table("users")]
public class User
{
    // UUID generated by PostgreSQL (gen_random_uuid())
    [Key]
    [Column("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    [Column("user_first")]
    public string UserFirst { get; set; } = string.Empty;

    [Column("user_last")]
    public string UserLast { get; set; } = string.Empty;

    [Column("user_region")]
    public string? UserRegion { get; set; }

    [Column("goal_id")]
    public long? GoalId { get; set; }

    [Column("user_img_src")]
    public string? UserImgSrc { get; set; }

    // Added by migration 006
    [Column("north_star_vision")]
    public string? NorthStarVision { get; set; }

    [Column("definition_of_success")]
    public string? DefinitionOfSuccess { get; set; }

    [Column("current_grade_level")]
    public string? CurrentGradeLevel { get; set; }

    [Column("streak_count")]
    public int StreakCount { get; set; }

    // Navigation
    public Goal? Goal { get; set; }
    public StudentPreference? StudentPreference { get; set; }
    public ICollection<ProgressStatus> ProgressStatuses { get; set; } = [];
    public ICollection<Meeting> MenteeMeetings { get; set; } = [];
    public ICollection<ResourceBookmark> ResourceBookmarks { get; set; } = [];
    public ICollection<Milestone> Milestones { get; set; } = [];
}
