-- ERD alignment migration:
-- - users: UUID/id + legacy profile columns -> INT/id + ERD columns (+ first/last/email/date_of_birth)
-- - goals: goal_id/title/milestones -> goalid/pi1..pi10
-- - progressstatus -> usergoals(goalid, user_id, progress)
-- - dependent user FK tables moved from UUID to INT user keys
--
-- Run: psql -U <user> -d upath_db -f db/migrations/007_erd_alignment_users_goals_usergoals.sql

BEGIN;

-- Guard: only run if legacy tables exist and target tables are not already in place.
DO $$
BEGIN
  IF to_regclass('public.users') IS NULL OR to_regclass('public.goals') IS NULL THEN
    RAISE EXCEPTION 'Expected legacy users/goals tables to exist before running ERD alignment.';
  END IF;
END $$;

DROP TABLE IF EXISTS _user_id_map;
CREATE TABLE _user_id_map (
  old_user_id UUID PRIMARY KEY,
  new_user_id INT NOT NULL UNIQUE
);

DROP TABLE IF EXISTS _goal_id_map;
CREATE TABLE _goal_id_map (
  old_goal_id BIGINT PRIMARY KEY,
  new_goal_id INT NOT NULL UNIQUE
);

ALTER TABLE IF EXISTS progressstatus RENAME TO progressstatus_legacy;
ALTER TABLE users RENAME TO users_legacy;
ALTER TABLE goals RENAME TO goals_legacy;

CREATE TABLE goals (
  goalid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pi1 VARCHAR(255) NOT NULL,
  pi2 VARCHAR(255) NOT NULL,
  pi3 VARCHAR(255),
  pi4 VARCHAR(255),
  pi5 VARCHAR(255),
  pi6 VARCHAR(255),
  pi7 VARCHAR(255),
  pi8 VARCHAR(255),
  pi9 VARCHAR(255),
  pi10 VARCHAR(255)
);

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  region VARCHAR(100),
  ethnicity VARCHAR(100),
  incomebracket INT,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  date_of_birth DATE,
  legacy_user_uuid UUID UNIQUE
);

INSERT INTO goals (goalid, pi1, pi2, pi3, pi4, pi5, pi6, pi7, pi8, pi9, pi10)
OVERRIDING SYSTEM VALUE
SELECT
  g.goal_id::INT,
  COALESCE(g.title, 'Unknown Goal'),
  COALESCE(g.milestone1, 'Not Set'),
  g.milestone2,
  g.milestone_n,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
FROM goals_legacy g
ORDER BY g.goal_id;

INSERT INTO _goal_id_map (old_goal_id, new_goal_id)
SELECT g.goal_id, g.goal_id::INT
FROM goals_legacy g;

INSERT INTO users (
  username,
  password,
  role,
  region,
  ethnicity,
  incomebracket,
  first_name,
  last_name,
  email,
  date_of_birth,
  legacy_user_uuid
)
SELECT
  LOWER(
    REGEXP_REPLACE(
      CONCAT(
        COALESCE(NULLIF(TRIM(u.user_first), ''), 'user'),
        '_',
        COALESCE(NULLIF(TRIM(u.user_last), ''), 'migrated')
      ),
      '[^a-zA-Z0-9_]+',
      '',
      'g'
    )
  ) || '_' || SUBSTRING(REPLACE(u.id::TEXT, '-', '') FOR 8) AS username,
  'TEMP_MIGRATE_RESET' AS password,
  'student' AS role,
  u.user_region AS region,
  'unspecified' AS ethnicity,
  0 AS incomebracket,
  COALESCE(NULLIF(TRIM(u.user_first), ''), 'Unknown') AS first_name,
  COALESCE(NULLIF(TRIM(u.user_last), ''), 'User') AS last_name,
  LOWER(
    COALESCE(NULLIF(TRIM(u.user_first), ''), 'user') || '.' ||
    COALESCE(NULLIF(TRIM(u.user_last), ''), 'migrated') || '.' ||
    SUBSTRING(REPLACE(u.id::TEXT, '-', '') FOR 8) ||
    '@example.com'
  ) AS email,
  NULL::DATE AS date_of_birth,
  u.id
FROM users_legacy u
ORDER BY u.id;

INSERT INTO _user_id_map (old_user_id, new_user_id)
SELECT u.legacy_user_uuid, u.id
FROM users u
WHERE u.legacy_user_uuid IS NOT NULL;

ALTER TABLE users DROP COLUMN legacy_user_uuid;

CREATE TABLE usergoals (
  goalid INT NOT NULL,
  user_id INT NOT NULL,
  progress INT NOT NULL DEFAULT 0,
  PRIMARY KEY (goalid, user_id),
  CONSTRAINT fk_usergoals_goal FOREIGN KEY (goalid) REFERENCES goals(goalid) ON DELETE CASCADE,
  CONSTRAINT fk_usergoals_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ck_usergoals_progress_range CHECK (progress >= 0 AND progress <= 100)
);

DO $$
BEGIN
  IF to_regclass('public.progressstatus_legacy') IS NOT NULL THEN
    INSERT INTO usergoals (goalid, user_id, progress)
    SELECT
      p.goal_id::INT,
      m.new_user_id,
      (
        (
          (CASE WHEN p.milestone1_is_complete THEN 1 ELSE 0 END) +
          (CASE WHEN p.milestone2_is_complete THEN 1 ELSE 0 END) +
          (CASE WHEN p.milestone_n_is_complete THEN 1 ELSE 0 END)
        ) * 100 / 3
      )::INT AS progress
    FROM progressstatus_legacy p
    JOIN _user_id_map m
      ON m.old_user_id = p.id
    ON CONFLICT (goalid, user_id) DO UPDATE SET progress = EXCLUDED.progress;
  END IF;
END $$;

-- meetings: mentee_id UUID -> INT
DO $$
BEGIN
  IF to_regclass('public.meetings') IS NOT NULL THEN
    ALTER TABLE meetings DROP CONSTRAINT IF EXISTS meetings_pkey;
    ALTER TABLE meetings DROP CONSTRAINT IF EXISTS fk_meeting_mentee;
    ALTER TABLE meetings ADD COLUMN IF NOT EXISTS mentee_id_new INT;

    UPDATE meetings mt
    SET mentee_id_new = m.new_user_id
    FROM _user_id_map m
    WHERE m.old_user_id = mt.mentee_id;

    ALTER TABLE meetings DROP COLUMN mentee_id;
    ALTER TABLE meetings RENAME COLUMN mentee_id_new TO mentee_id;
    ALTER TABLE meetings ALTER COLUMN mentee_id SET NOT NULL;
    ALTER TABLE meetings ADD CONSTRAINT meetings_pkey PRIMARY KEY (mentor_id, mentee_id);
    ALTER TABLE meetings
      ADD CONSTRAINT fk_meeting_mentee
      FOREIGN KEY (mentee_id) REFERENCES users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- student_preferences: user_id UUID -> INT
DO $$
BEGIN
  IF to_regclass('public.student_preferences') IS NOT NULL THEN
    ALTER TABLE student_preferences DROP CONSTRAINT IF EXISTS student_preferences_pkey;
    ALTER TABLE student_preferences DROP CONSTRAINT IF EXISTS student_preferences_user_id_fkey;
    ALTER TABLE student_preferences ADD COLUMN IF NOT EXISTS user_id_new INT;

    UPDATE student_preferences sp
    SET user_id_new = m.new_user_id
    FROM _user_id_map m
    WHERE m.old_user_id = sp.user_id;

    ALTER TABLE student_preferences DROP COLUMN user_id;
    ALTER TABLE student_preferences RENAME COLUMN user_id_new TO user_id;
    ALTER TABLE student_preferences ALTER COLUMN user_id SET NOT NULL;
    ALTER TABLE student_preferences ADD CONSTRAINT student_preferences_pkey PRIMARY KEY (user_id);
    ALTER TABLE student_preferences
      ADD CONSTRAINT student_preferences_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- resource_bookmarks: user_id UUID -> INT
DO $$
BEGIN
  IF to_regclass('public.resource_bookmarks') IS NOT NULL THEN
    ALTER TABLE resource_bookmarks DROP CONSTRAINT IF EXISTS resource_bookmarks_pkey;
    ALTER TABLE resource_bookmarks DROP CONSTRAINT IF EXISTS resource_bookmarks_user_id_fkey;
    ALTER TABLE resource_bookmarks ADD COLUMN IF NOT EXISTS user_id_new INT;

    UPDATE resource_bookmarks rb
    SET user_id_new = m.new_user_id
    FROM _user_id_map m
    WHERE m.old_user_id = rb.user_id;

    ALTER TABLE resource_bookmarks DROP COLUMN user_id;
    ALTER TABLE resource_bookmarks RENAME COLUMN user_id_new TO user_id;
    ALTER TABLE resource_bookmarks ALTER COLUMN user_id SET NOT NULL;
    ALTER TABLE resource_bookmarks ADD CONSTRAINT resource_bookmarks_pkey PRIMARY KEY (user_id, resource_id);
    ALTER TABLE resource_bookmarks
      ADD CONSTRAINT resource_bookmarks_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- milestones: user_id UUID -> INT
DO $$
BEGIN
  IF to_regclass('public.milestones') IS NOT NULL THEN
    ALTER TABLE milestones DROP CONSTRAINT IF EXISTS milestones_user_id_fkey;
    ALTER TABLE milestones ADD COLUMN IF NOT EXISTS user_id_new INT;

    UPDATE milestones ms
    SET user_id_new = m.new_user_id
    FROM _user_id_map m
    WHERE m.old_user_id = ms.user_id;

    ALTER TABLE milestones DROP COLUMN user_id;
    ALTER TABLE milestones RENAME COLUMN user_id_new TO user_id;
    ALTER TABLE milestones ALTER COLUMN user_id SET NOT NULL;
    ALTER TABLE milestones
      ADD CONSTRAINT milestones_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  END IF;
END $$;

DROP TABLE IF EXISTS progressstatus_legacy;
DROP TABLE IF EXISTS users_legacy;
DROP TABLE IF EXISTS goals_legacy;
DROP TABLE IF EXISTS _goal_id_map;
DROP TABLE IF EXISTS _user_id_map;

COMMIT;
